### PR TITLE
Remove spec/ and .gitignored files from gemspec.files

### PR DESCRIPTION
**Pull request by nfm**

### CODE REVIEW

**Comment by eliotsykes** [comment]
👍

**Comment by nfm** [comment]
@peterkeen FWIW I haven't yet signed the CLA because I haven't had time to read and properly understand it. We're using Payola in a work context and I need to be relatively cautious about what I sign for (not really for this PR, but possibly for past or future ones) and it's not super clear to me what the CLA covers.

It would be good if there was some information in the README about this, and perhaps what the purpose of the CLA is. Is it a standard agreement? Is it specific language for Cora Street Press? etc.

I'd consider the current CLA a bit of a barrier to entry, so if you need this in place, it could be good to provide some high-level plain language as to why it's required, what it covers, etc.

**Comment by peterkeen** [comment]
@nfm I understand. The CLA is the boilerplate one that SAP provides as part of cla-assistant. It does two important things:

* Grants Cora Street Press LLC (my book and software publishing company) a royalty free copyright license to any and all contributions.

* Grants Cora Street Press a royalty free patent license to any and all contributions. 

This allows me to do things like change the license, sell it under a different license, sell extensions, etc.

Does that make sense? Please feel free to run it past your attorney before signing. It's not granting me license to anything other than the changes you request to be pulled into payola proper, not your Rails application.

**Comment by nfm** [comment]
Thanks @peterkeen, that makes sense. I've read the CLA carefully and it looks ok to me. I guess I was a little unsure because it wasn't an off-the-shelf thing. I was under the impression that the licence (LGPLv3) used for Payola achieved the same things as the CLA - is that not the case?

**Comment by peterkeen** [comment]
Thanks @nfm. The LGPL accomplishes some of that, but it wouldn't let me do something like sell a dual-licensed Payola or something. It also just makes the "chain of custody" so to speak quite a bit easier to understand.

**Pull request merged**
